# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "simple store locator"
handle = "storelocator-vdesignu"
application_url = "https://storelocator.vdesignu.com"
embedded = true
client_id = "817cac4e2f1d3f929fb87ef43571d6e9"

[build]
automatically_update_urls_on_dev = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://storelocator.vdesignu.com/auth/callback",
  "https://storelocator.vdesignu.com/api/auth/callback",
]

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app_subscriptions/update"
  topics = [ "app_subscriptions/update" ]

[app_proxy]
url = "https://storelocator.vdesignu.com/proxy"
subpath = "store-locator"
prefix = "apps"

[pos]
embedded = false
